name: notejet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  webview_flutter: ^2.0.10
  google_mobile_ads: ^0.13.2+1
  onesignal_flutter: ^3.1.0
  path_provider: ^2.0.2
  dio: any
  url_launcher: ^6.0.9

  

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/



